import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ApolloWrapper } from "@/app/ApolloWrapper";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "АРМ руководителя",
  description: "Generated by create next app"
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="ru">
  <body>
  <ApolloWrapper>
    <AntdRegistry>{children}</AntdRegistry>
  </ApolloWrapper>
  </body>
  </html>
);

export default RootLayout;
